// src/components/forms/QuoteForm.svelte
<script>
  const TURNSTILE_SITE_KEY = import.meta.env.PUBLIC_TURNSTILE_SITE_KEY
  import { actions, isInputError } from 'astro:actions'
  import Input from './Input.svelte'
  import { DateInput } from 'date-picker-svelte'
  import { turnstile } from '@svelte-put/cloudflare-turnstile'
  let { quoteFormTitle } = $props()
  let isLoading = $state(false)

  let form = $state({
    serviceType: 'Moving',
    firstName: '',
    lastName: '',
    initialDeliveryZip: '',
    finalDeliveryZip: '',
    deliveryDate: new Date(),
    email: '',
    phone: '',
    storeItType: '',
    cfTurnstileResponse: '',
    errors: {},
  })

  async function handleSubmit(event) {
    event.preventDefault()
    isLoading = true
    form.errors = {}
    const result = await actions.quoteForm(form)
    if (isInputError(result.error)) {
      console.log(result.error)
      form.errors = Object.fromEntries(
        Object.entries(result.error.fields).map(([key, value]) => [
          key,
          Array.isArray(value) ? value[0] : value,
        ])
      )
    } else {
      if (result.data.success) {
        console.log('Success:', result.data)
        isLoading = false
        window.location.href = result.data.successUrl
      }
    }
    isLoading = false
  }
</script>

<form id="quote-form" method="POST" onsubmit={handleSubmit}>
  <h2 class="md:text-3xl text-xl text-center font-bold block">
    {quoteFormTitle}
  </h2>
  <div class="flex justify-around items-center my-6 gap-4">
    <button
      type="button"
      class={`py-3 px-4 rounded-md flex-1 shadow-[0px_4px_8px_0px_#00000040] transition-colors cursor-pointer ${form.serviceType === 'Moving' ? 'bg-primary text-white shadow-md' : 'bg-gray-200 text-black hover:bg-gray-300'}`}
      onclick={() => (form.serviceType = 'Moving')}
    >
      Moving
    </button>
    <button
      type="button"
      class={`py-3 px-4 rounded-md shadow-[0px_4px_8px_0px_#00000040] transition-colors cursor-pointer flex-1 ${form.serviceType === 'Storage' ? 'bg-primary text-white shadow-md' : 'bg-gray-200 text-black hover:bg-gray-300'}`}
      onclick={() => (form.serviceType = 'Storage')}
    >
      Storage
    </button>
    <button
      type="button"
      class={`py-3 px-4 rounded-md shadow-[0px_4px_8px_0px_#00000040] transition-colors cursor-pointer flex-1 ${form.serviceType === 'Storage & Moving' ? 'bg-primary text-white shadow-md' : 'bg-gray-200 text-black hover:bg-gray-300'}`}
      onclick={() => (form.serviceType = 'Storage & Moving')}
    >
      Both
    </button>
  </div>
  <div class="space-y-2">
    {#if form.serviceType === 'Storage' || form.serviceType === 'Storage & Moving'}
      <h3 class="italic text-dark">Where would you like to store your container?</h3>
      <button
        type="button"
        class={`py-1 px-4 rounded-md transition-colors flex-1 mr-3 ${form.storeItType === 'My Location' ? 'bg-primary text-white shadow-md' : 'bg-gray-300 shadow text-black cursor-pointer hover:bg-gray-300'}`}
        onclick={() => (form.storeItType = 'My Location')}
      >
        My Location
      </button>
      <button
        type="button"
        class={`py-1 px-4 rounded-md transition-colors flex-1 ${form.storeItType === 'MI-BOX Location' ? 'bg-primary text-white shadow-md' : 'bg-gray-300 shadow text-black cursor-pointer hover:bg-gray-300'}`}
        onclick={() => (form.storeItType = 'MI-BOX Location')}
      >
        MI-BOX Location
      </button>
    {/if}
    <div class="grid grid-cols-1 md:grid-cols-2 gap-3">
      <Input
        forId="first-name"
        label="First Name"
        placeholder="Bob"
        bind:value={form.firstName}
        errors={form.errors.firstName}
      />
      <Input
        forId="last-name"
        label="Last Name"
        placeholder="Smith"
        bind:value={form.lastName}
        errors={form.errors.lastName}
      />
    </div>
    <div class="flex gap-2">
      <div class="w-full">
        <Input
          forId="initial-delivery-zip"
          label="Initial Delivery Zip Code"
          placeholder="34240"
          bind:value={form.initialDeliveryZip}
          errors={form.errors.initialDeliveryZip}
        />
      </div>
      {#if form.serviceType === 'move-it'}
        <div class="w-full">
          <Input
            forId="final-delivery-zip"
            label="Final Delivery Zip Code"
            placeholder="34240"
            bind:value={form.finalDeliveryZip}
            errors={form.errors.finalDeliveryZip}
          />
        </div>
      {/if}
    </div>
    <div>
      <label for="delivery-date" class="block text-sm/6 font-medium text-gray-900"
        >Delivery Date</label
      >
      <DateInput
        class="block w-full rounded-md bg-white p-0 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-primary sm:text-sm/6"
        id="delivery-date"
        bind:value={form.deliveryDate}
        max={new Date('2030-12-31')}
        format="MM-dd-yyyy"
        closeOnSelection
      />
      {#if form.errors?.deliveryDate}
        <p class="text-red-800">{form.errors.deliveryDate}</p>
      {/if}
    </div>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-3">
      <Input
        forId="email"
        label="Email"
        placeholder="user@email.com"
        bind:value={form.email}
        errors={form.errors.email}
      />
      <Input
        forId="phone"
        label="Phone"
        placeholder="222.222.2222"
        bind:value={form.phone}
        errors={form.errors.phone}
      />
    </div>
    <div
      use:turnstile
      turnstile-sitekey={TURNSTILE_SITE_KEY}
      turnstile-theme="light"
      turnstile-size="normal"
      turnstile-language="en"
      turnstile-response-field-name="turnstile"
      turnstile-response-field
      turnstile-feedback-enabled
      onturnstile={(e) => (form.cfTurnstileResponse = e.detail.token)}
    ></div>
    {#if form.errors?.cfTurnstileResponse}
      <p class="text-red-800">{form.errors.cfTurnstileResponse}</p>
    {/if}
    <button
      type="submit"
      disabled={isLoading}
      class="submit-btn shadow-[0px_4px_8px_0px_#00000040] cursor-pointer"
    >
      {#if isLoading}
        Submitting...
        <svg
          class="animate-spin h-5 w-5"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
        >
          <circle
            class="opacity-25"
            cx="12"
            cy="12"
            r="10"
            stroke="currentColor"
            stroke-width="4"
          />
          <path
            class="opacity-75"
            fill="currentColor"
            d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
          />
        </svg>
      {:else}
        Get your Quote
      {/if}
    </button>
  </div>
</form>

<style>
  .submit-btn {
    background: var(--color-secondary);
    display: flex;
    gap: 0.5rem;
    justify-content: center;
    align-items: center;
    border-radius: 0.25rem;
    font-size: 0.875rem;
    line-height: 1.25rem;
    font-weight: 500;
    color: #ffffff;
    white-space: nowrap;
    padding: 0.5rem 1rem;
  }
  @media (min-width: 1024px) {
    .submit-btn {
      padding-top: 0.75rem;
      padding-bottom: 0.75rem;
      padding-left: 1.25rem;
      padding-right: 1.25rem;
      font-size: 1.125rem;
      line-height: 1.75rem;
      font-weight: 600;
    }
  }
</style>

// src/components/forms/QuoteForm.jsx
import React, { useState } from "react";
import { useForm } from "react-hook-form";
import DatePicker from "react-datepicker";
import { Turnstile } from "@marsidev/react-turnstile";
import "react-datepicker/dist/react-datepicker.css";
import { actions, isInputError } from "astro:actions";

const TURNSTILE_SITE_KEY = import.meta.env.PUBLIC_TURNSTILE_SITE_KEY;

export default function QuoteForm({
  quoteFormTitle = "Get a Free Quote",
  promoCode = "",
  phoneNumber,
}) {
  const {
    register,
    handleSubmit,
    setValue,
    watch,
    formState: { errors, isSubmitting },
  } = useForm({
    defaultValues: {
      serviceType: "Moving",
      firstName: "",
      lastName: "",
      initialDeliveryZip: "",
      finalDeliveryZip: "",
      deliveryDate: new Date(),
      email: "",
      phone: "",
      storeItType: "",
      promoCode,
      cfTurnstileResponse: "",
    },
  });

  const serviceType = watch("serviceType");
  const storeItType = watch("storeItType");

  const onSubmit = async (data) => {
    const result = await actions.quoteForm(data);
    console.log("Form submission result:", result);
    if (isInputError(result.error)) {
      form.errors = Object.fromEntries(
        Object.entries(result.error.fields).map(([key, value]) => [
          key,
          Array.isArray(value) ? value[0] : value,
        ])
      );
    } else {
      if (result.data.success) {
        window.location.href = result.data.successUrl;
      }
    }
  };

  return (
    <form
      onSubmit={handleSubmit(onSubmit)}
      className="space-y-4 max-w-3xl mx-auto"
    >
      <h2 className="text-xl md:text-3xl text-center font-bold">
        {quoteFormTitle}
      </h2>

      <div className="flex justify-around items-center my-6 gap-4">
        {["Moving", "Storage", "Storage & Moving"].map((type) => (
          <button
            key={type}
            type="button"
            className={`py-3 px-4 rounded-md flex-1 transition-colors shadow ${
              serviceType === type
                ? "bg-primary text-white shadow-md"
                : "bg-gray-200 hover:bg-gray-300"
            }`}
            onClick={() => setValue("serviceType", type)}
          >
            {type === "Storage & Moving" ? "Both" : type}
          </button>
        ))}
      </div>

      {(serviceType === "Storage" || serviceType === "Storage & Moving") && (
        <div className="space-y-2">
          <h3 className="italic text-dark">
            Where would you like to store your container?
          </h3>
          <div className="flex gap-2">
            {["My Location", "MI-BOX Location"].map((opt) => (
              <button
                key={opt}
                type="button"
                className={`py-1 px-4 rounded-md flex-1 transition-colors shadow ${
                  storeItType === opt
                    ? "bg-primary text-white shadow-md"
                    : "bg-gray-300 hover:bg-gray-300"
                }`}
                onClick={() => setValue("storeItType", opt)}
              >
                {opt}
              </button>
            ))}
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        <div>
          <label>First Name</label>
          <input
            {...register("firstName", { required: true })}
            placeholder="Bob"
            className="input"
          />
          {errors.firstName && (
            <p className="text-red-600">First name is required</p>
          )}
        </div>
        <div>
          <label>Last Name</label>
          <input
            {...register("lastName", { required: true })}
            placeholder="Smith"
            className="input"
          />
          {errors.lastName && (
            <p className="text-red-600">Last name is required</p>
          )}
        </div>
      </div>

      <div
        className={`grid grid-cols-1 ${
          (serviceType === "Moving" || serviceType === "Storage & Moving") &&
          "md:grid-cols-2"
        }
        } gap-3`}
      >
        <div className="">
          <label>Initial Delivery Zip Code</label>
          <input
            {...register("initialDeliveryZip", { required: true })}
            placeholder="34240"
            className="input"
          />
          {errors.initialDeliveryZip && (
            <p className="text-red-600">Required</p>
          )}
        </div>
        {(serviceType === "Moving" || serviceType === "Storage & Moving") && (
          <div>
            <label>Final Delivery Zip Code</label>
            <input
              {...register("finalDeliveryZip", { required: true })}
              placeholder="34240"
              className="input"
            />
            {errors.finalDeliveryZip && (
              <p className="text-red-600">Required</p>
            )}
          </div>
        )}
      </div>

      <div className="flex flex-col">
        <label>Delivery Date</label>
        <DatePicker
          selected={watch("deliveryDate")}
          onChange={(date) => setValue("deliveryDate", date)}
          dateFormat="MM-dd-yyyy"
          className="input"
        />
        {errors.deliveryDate && <p className="text-red-600">Required</p>}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        <div>
          <label>Email</label>
          <input
            {...register("email", { required: true })}
            placeholder="you@example.com"
            className="input"
          />
          {errors.email && <p className="text-red-600">Email is required</p>}
        </div>
        <div>
          <label>Phone</label>
          <input
            {...register("phone", { required: true })}
            placeholder="222.222.2222"
            className="input"
          />
          {errors.phone && <p className="text-red-600">Phone is required</p>}
        </div>
      </div>

      <div>
        <label>Promo Code</label>
        <input value={promoCode} readOnly className="input bg-gray-100" />
      </div>

      <Turnstile
        siteKey={TURNSTILE_SITE_KEY}
        onSuccess={(token) => setValue("cfTurnstileResponse", token)}
        options={{ theme: "light" }}
      />
      {errors.cfTurnstileResponse && (
        <p className="text-red-600">Captcha required</p>
      )}

      <button
        type="submit"
        disabled={isSubmitting}
        className="submit-btn w-full flex justify-center items-center"
      >
        {isSubmitting ? (
          <>
            Submitting...
            <svg className="animate-spin h-5 w-5 ml-2" viewBox="0 0 24 24">
              <circle
                cx="12"
                cy="12"
                r="10"
                stroke="currentColor"
                strokeWidth="4"
                className="opacity-25"
              />
              <path
                fill="currentColor"
                className="opacity-75"
                d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
              />
            </svg>
          </>
        ) : (
          "Get your Quote"
        )}
      </button>
    </form>
  );
}
